print('Welcome to the Temperature Conversion App')
faren = float(input('\nWhat is the given temperature in degrees Fahrenheit: '))
print(f'\nDegrees Fahrenheit: {faren}')
print(f'Degrees Celsius: {round((faren - 32) * 5 / 9 , 4)}')
print(f'Degrees Kelvin: {round((faren - 32) * 5 / 9 + 273.15 , 4)}')