print('\nWelcome to the Coin Toss App')
print('\nI will flip a coin a set number of times.')
cantF = int(input('How many times would you like me to flip the coin:'))
see = input('Would you like to see the result of each flip (y/n): ')
print('\n\nFlipping!!\n\n')
print('hola')